substitutions:
  name: "esp32-c6-1"
  friendly_name: "ESP32_C6_1"

esphome:
  name: "esp32-c6-1"
  friendly_name: "ESP32_C6_1"

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "LYZkpDUXPwUD2glv64Di58KiJOsSlFc7duQfzZUml/U="

ota:
  - platform: esphome
    password: "608c96fe5b1980ca0fd185e26ed0e1ad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # manual_ip:
  #   static_ip: 192.168.1.101
  #   gateway: 192.168.1.1
  #   subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C6-1"
    password: "test_esp"

captive_portal:

web_server:


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "ESP IP Address"
      address_0:
        name: "ESP IP Address 0"
      address_1:
        name: "ESP IP Address 1"
    ssid:
      name: "ESP Connected SSID"
    bssid:
      name: "ESP Connected BSSID"
    mac_address:
      name: "ESP Mac Wifi Address"
    scan_results:
      name: "ESP Latest Scan Results"
    dns_address:
      name: "ESP DNS Address"

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

button:
- platform: restart
  name: "Restart"