substitutions:
  name: "esp32-c6-1"
  friendly_name: "ESP32_C6_1"

esphome:
  name: "esp32-c6-1"
  friendly_name: "ESP32_C6_1"
  # https://github.com/esphome/esphome/pull/1651
  platformio_options:
    build_flags: "-DI2C_NUM_1=I2C_NUM_0"
  on_boot:
    then:
      - sensor.template.publish:
          id: co2_ppm_1m
          state: !lambda 'return id(co2_1min);'
      - sensor.template.publish:
          id: co2_ppm_2m
          state: !lambda 'return id(co2_2min);'
      - sensor.template.publish:
          id: co2_ppm_3m
          state: !lambda 'return id(co2_3min);'
      - sensor.template.publish:
          id: co2_ppm_4m
          state: !lambda 'return id(co2_4min);'
      - sensor.template.publish:
          id: co2_ppm_5m
          state: !lambda 'return id(co2_5min);'
      - sensor.template.publish:
          id: co2_ppm_15m
          state: !lambda 'return id(co2_15min);'
      - sensor.template.publish:
          id: co2_ppm_30m
          state: !lambda 'return id(co2_30min);'
      - sensor.template.publish:
          id: co2_ppm_1h
          state: !lambda 'return id(co2_1h);'
      - sensor.template.publish:
          id: co2_ppm_24h
          state: !lambda 'return id(co2_24h);'
  on_shutdown:
    then:
      - globals.set:
          id: co2_1min
          value: !lambda 'return id(co2_ppm_1m).state;'
      - globals.set:
          id: co2_2min
          value: !lambda 'return id(co2_ppm_2m).state;'
      - globals.set:
          id: co2_3min
          value: !lambda 'return id(co2_ppm_3m).state;'
      - globals.set:
          id: co2_4min
          value: !lambda 'return id(co2_ppm_4m).state;'
      - globals.set:
          id: co2_5min
          value: !lambda 'return id(co2_ppm_5m).state;'
      - globals.set:
          id: co2_15min
          value: !lambda 'return id(co2_ppm_15m).state;'
      - globals.set:
          id: co2_30min
          value: !lambda 'return id(co2_ppm_30m).state;'
      - globals.set:
          id: co2_1h
          value: !lambda 'return id(co2_ppm_1h).state;'
      - globals.set:
          id: co2_24h
          value: !lambda 'return id(co2_ppm_24h).state;'

# https://esphome.io/components/esp32
esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      # https://community.home-assistant.io/t/esp32-c6-zigbee2mqtt/713289/4
      # CONFIG_ZB_ENABLED: y
      # CONFIG_ZB_ZED: y
      # CONFIG_ZB_RADIO_NATIVE: y
      # ZB_ED_ROLE: y
    version: "5.3.1"
    platform_version: 6.9.0

# https://github.com/esphome/issues/issues/6639#issuecomment-2669790604
external_components:
  - source: github://pr#8283
    components: [ i2c ]

logger:
  level: INFO
api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_portable
      password: !secret wifi_password_portable
  # Board will host Wifi by itself
  ap:
    ssid: "${friendly_name}"
    password: !secret fall_back_wifi_password
    manual_ip:
        static_ip: !secret ap_static_ip_portable
        gateway: !secret ap_static_gateway
        subnet: 255.255.255.0
        dns1: !secret ap_static_dns
        dns2: 8.8.8.8
  # When no API connection
  reboot_timeout: 0s
  # Do not fast connect when portable
  # fast_connect: true


# Save CO2 history levels between reboots
globals:
  - id: co2_1min
    type: int
    restore_value: true
  - id: co2_2min
    type: int
    restore_value: true
  - id: co2_3min
    type: int
    restore_value: true
  - id: co2_4min
    type: int
    restore_value: true
  - id: co2_5min
    type: int
    restore_value: true
  - id: co2_15min
    type: int
    restore_value: true
  - id: co2_30min
    type: int
    restore_value: true
  - id: co2_1h
    type: int
    restore_value: true
  - id: co2_24h
    type: int
    restore_value: true


web_server:
  port: 80
  version: 3
  sorting_groups:
  - id: sorting_group_co2
    name: "CO2 Values (SDC41)"
    sorting_weight: -1
  - id: sorting_group_statistics
    name: "Statistics"
    sorting_weight: 10
  - id: sorting_group_calibration
    name: "Calibration Values"
    sorting_weight: 40
  - id: sorting_group_diagnostic
    name: "Diagnostic info"
    sorting_weight: 60
  - id: sorting_group_service
    name: "Service"
    sorting_weight: 90

# https://github.com/esphome/issues/issues/6639
i2c:
  sda: GPIO06
  scl: GPIO07
  scan: false
  id: bus_a

sensor:
  # https://esphome.io/components/sensor/scd4x.html#configuration-variables
  # https://esphome.io/components/sensor/index.html#sensor-filters
  - platform: scd4x
    i2c_id: bus_a
    address: 0x62
    id: scd41_esp32
    automatic_self_calibration: true
    measurement_mode: periodic
    co2:
      name: "CO2"
      id: "ppm_co2"
      state_class: 'measurement'
      device_class: "carbon_dioxide"
      unit_of_measurement: "ppm"
      icon: mdi:molecule-co2
      filters:
      - skip_initial: 3
      web_server:
        sorting_group_id: sorting_group_co2
      on_value:
        then:
          - lambda: |-
              float co2 = std::min(float(2000), x);
              auto t = (co2-440)/(2000 - 440);
              auto interpolated = ESPHSVColor(uint8_t((1-t)*96), 255, 32);
              auto inter_rgb = interpolated.to_rgb();

              auto call = id(co2light).turn_on();
              call.set_rgb(inter_rgb.red / 255.0, inter_rgb.green / 255.0, inter_rgb.blue / 255.0);
              call.set_brightness(1);
              call.perform();
    temperature:
      name: "Temperature"
      id: "temperature"
      state_class: 'measurement'
      device_class: "temperature"
      accuracy_decimals: 2
      filters:
      - skip_initial: 3
      web_server:
        sorting_group_id: sorting_group_co2
    humidity:
      name: "Humidity"
      id: "humidity"
      state_class: 'measurement'
      device_class: "humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 2
      filters:
      - skip_initial: 3
      web_server:
        sorting_group_id: sorting_group_co2
    update_interval: 5s
  # Store values for some time
  # 1 min
  - platform: template
    name: "ppm 1min"
    id: co2_ppm_1m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 1
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 1
  # 2 min
  - platform: template
    name: "ppm 2min"
    id: co2_ppm_2m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 2
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 2
  # 3 min
  - platform: template
    name: "ppm 3min"
    id: co2_ppm_3m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 3
  # 4 min
  - platform: template
    name: "ppm 4min"
    id: co2_ppm_4m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 4
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 4
  # 5 min
  - platform: template
    name: "ppm 5min"
    id: co2_ppm_5m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 5
  # 15 min
  - platform: template
    name: "ppm 15min"
    id: co2_ppm_15m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 6
  # 30 min
  - platform: template
    name: "ppm 30min"
    id: co2_ppm_30m
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 30
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 7
  # 1 hour
  - platform: template
    name: "ppm 1h"
    id: co2_ppm_1h
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 60
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 8
  # 24 hours
  - platform: template
    name: "ppm 24h"
    id: co2_ppm_24h
    icon: mdi:molecule-co2
    unit_of_measurement: ppm
    lambda: |-
      return id(ppm_co2).state;
    update_interval: 60s
    filters:
      - sliding_window_moving_average:
          window_size: 1440
          send_every: 1
          send_first_at: 1
    web_server:
      sorting_group_id: sorting_group_statistics
      sorting_weight: 9
    
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
    web_server:
      sorting_group_id: sorting_group_diagnostic

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    web_server:
      sorting_group_id: sorting_group_diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${friendly_name}  WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    device_class: ""
    web_server:
      sorting_group_id: sorting_group_diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    bssid:
      name: "${friendly_name} Connected BSSID"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    mac_address:
      name: "${friendly_name} Mac Wifi Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    dns_address:
      name: "${friendly_name} DNS Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic

button:
  - platform: restart
    name: "Restart"
    web_server:
      sorting_group_id: sorting_group_service

# https://gist.github.com/baldowl/a413c2a08c10bc62c1a72328caac98c1?permalink_comment_id=5496287#gistcomment-5496287
light:
  - platform: esp32_rmt_led_strip
    name: Status LED
    id: co2light
    pin: GPIO8
    rgb_order: GRB
    num_leds: 1
    chipset: ws2812
    web_server: 
      sorting_group_id: sorting_group_service

# END