substitutions:
  name: "esp32-c6-1"
  friendly_name: "ESP32_C6_1"

esphome:
  # ESP32-C6-WROOM-1-N8
  name: "esp32-c6-1"
  friendly_name: "ESP32_C6_1"

# https://esphome.io/components/esp32.html#id2
# https://github.com/espressif/esp-idf/releases
# https://github.com/platformio/platform-espressif32
# https://docs.platformio.org/en/latest/boards/espressif32/esp32-c6-devkitc-1.html#board-espressif32-esp32-c6-devkitc-1
esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    # https://github.com/esphome/issues/issues/6639#issuecomment-2740709572
    version: 5.3.2
    platform_version: 53.03.11
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
      CONFIG_ZB_ENABLED: y
      CONFIG_ZB_RADIO_NATIVE: y
      CONFIG_ZB_ZED: y
      ZB_ED_ROLE: y

    # Zigbee:
    # https://github.com/luar123/esphome_zb_sensor
    # https://github.com/DmytroML/ESP36C6_Zigbee_PZEM-004t
    # https://github.com/espressif/esp-zigbee-sdk/tree/main/examples
    # https://github.com/espressif/esp-idf/tree/master/examples/zigbee/light_sample

    # Experiments:
    # version: dev
    # platform_version: dev

    # version: "5.4.0"  # https://github.com/espressif/esp-idf/releases/tag/v5.4
    # platform_version: 6.10.0  # https://github.com/platformio/platform-espressif32/releases/tag/v6.10.0
    # platform_version: 6.9.0
    # platform_version: 6.8.1

    # for LED: https://gist.github.com/baldowl/a413c2a08c10bc62c1a72328caac98c1
    # version: 5.1.2 # latest version when tested with ESPHome 2023.11.06
    # platform_version: 6.4.0 # latest version when tested with ESPHome 2023.11.06

    # https://github.com/esphome/issues/issues/5864#issuecomment-2380417718
    # version: "5.3.0"
    # platform_version: 6.8.1

    # https://github.com/esphome/issues/issues/5864#issuecomment-2460380038
    # version: 5.2.1

    # Works
    # https://www.reddit.com/r/esp32/comments/1fh8nup/comment/lqm1hvh/
    version: "5.3.1"
    platform_version: 6.9.0

#This is to make sure adc compiles or else it will throw an error
external_components:
  - source:
      # https://github.com/lboue/esphome/blob/adc_oneshot/esphome/components/adc
      type: git
      url: https://github.com/lboue/esphome
      ref: adc_oneshot
    components: [ adc ]
    refresh: 0s

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG

ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name}"
    password: !secret fall_back_wifi_password
  reboot_timeout: 900s
  fast_connect: true

# Skip for faster use
# api:
  # encryption:
    # key: !secret api_key

captive_portal:

# # Slow start
# esp32_ble_tracker:
#   scan_parameters:
#     interval: 1100ms
#     window: 1100ms
#     active: true

# bluetooth_proxy:
#   active: true

web_server:
  port: 80
  version: 3
  sorting_groups:
  - id: sorting_group_controls
    name: "Controls"
    sorting_weight: 10
  - id: sorting_group_monitor
    name: "Sensor monitor"
    sorting_weight: 10
  - id: sorting_group_calibration
    name: "Calibration"
    sorting_weight: 50
  - id: sorting_group_diagnostic
    name: "Diagnostic info"
    sorting_weight: 60
  - id: sorting_group_service
    name: "Service"
    sorting_weight: 90

uart:
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600

# i2c:
#   id: bus_a
#   # setup_priority: -100 # fix for interfering with wifi!
#   sda: GPIO21
#   scl: GPIO22
#   scan: True # show discovered devices

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic
      address_0:
        name: "${friendly_name} IP Address 0"
        web_server:
          sorting_group_id: sorting_group_diagnostic
      address_1:
        name: "${friendly_name} IP Address 1"
        web_server:
          sorting_group_id: sorting_group_diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    bssid:
      name: "${friendly_name} Connected BSSID"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    mac_address:
      name: "${friendly_name} Mac Wifi Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    scan_results:
      name: "${friendly_name} Latest Scan Results"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    dns_address:
      name: "${friendly_name} DNS Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s
    web_server:
          sorting_group_id: sorting_group_diagnostic

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    web_server:
      sorting_group_id: sorting_group_diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${friendly_name}  WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    device_class: ""
    web_server:
      sorting_group_id: sorting_group_diagnostic

  # https://github.com/esphome/issues/issues/5363#issuecomment-2269543371
  - platform: adc
    pin: GPIO2
    name: "Gas ADC (CO)"
    update_interval: 1s
    filters:
      - multiply: 3.3
    accuracy_decimals: 4
    unit_of_measurement: V
    id: sensor_volt_co
    web_server:
      sorting_group_id: sorting_group_calibration

  - platform: adc
    pin: GPIO3
    name: "Gas ADC (Alcohol)"
    update_interval: 1s
    filters:
      - multiply: 3.3
    accuracy_decimals: 4
    unit_of_measurement: V
    id: sensor_volt_alco
    web_server:
      sorting_group_id: sorting_group_calibration

output:
  # https://esphome.io/guides/configuration-types#config-pin-schema
  # # Led is uncontrollable
  # # Onboard LED
  - platform: gpio
    id: output_GPIO08
    pin: 
        number: GPIO08
        allow_other_uses: true
        mode:
          output: true
          pulldown: true

  - platform: gpio
    id: output_GPIO09
    pin: 
        number: GPIO09
        allow_other_uses: true
        inverted: true
        mode:
          input: true
          pullup: true

  - platform: gpio
    id: output_GPIO18
    pin: 
        number: GPIO18
        allow_other_uses: true

# Button
button:
- platform: restart
  id: button_restart
  name: "Restart"
  web_server:
    sorting_group_id: sorting_group_service

# - platform: template
#   id: button_GPIO08
#   name: "Button (GPIO08)"
#   on_press:
#     then:
#       - logger.log: Button Pressed GPIO08
#       - switch.toggle: pin_GPIO08
#   web_server:
#     sorting_group_id: sorting_group_controls

# - platform: output
#   id: button_GPIO08_time
#   name: "Button (GPIO08) 500ms"
#   output: output_GPIO08
#   duration: 500ms
#   on_press:
#     then:
#       - logger.log: Button Pressed GPIO08 with time
#   web_server:
#     sorting_group_id: sorting_group_controls

- platform: template
  id: button_GPIO09
  name: "Button (GPIO09)"
  on_press:
    then:
      - logger.log: Button Pressed GPIO09
      - switch.toggle: pin_GPIO09
  web_server:
    sorting_group_id: sorting_group_controls

- platform: output
  id: button_GPIO18
  name: "Button (GPIO18) 500ms"
  output: output_GPIO18
  duration: 500ms
  on_press:
    then:
      - logger.log: Button Pressed GPIO18
  web_server:
    sorting_group_id: sorting_group_controls

# https://gist.github.com/baldowl/a413c2a08c10bc62c1a72328caac98c1?permalink_comment_id=5496287#gistcomment-5496287
light:
  - platform: esp32_rmt_led_strip
    name: Status LED
    id: co2light
    pin: GPIO8
    rgb_order: GRB
    num_leds: 1
    chipset: ws2812
    effects:
      - random:
      - strobe:
      - flicker:
    web_server: 
      sorting_group_id: sorting_group_service

switch:
  - platform: gpio
    id: pin_GPIO09
    name: "(GPIO09)"
    pin:
      number: GPIO09
      mode: output
      allow_other_uses: true
      inverted: false
    on_turn_on:
    - logger.log: "Switch (GPIO09) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO09) Turned Off!"

  - platform: gpio
    id: pin_GPIO18
    name: "(GPIO18)"
    pin:
      number: GPIO18
      mode: output
      allow_other_uses: true
      inverted: false
    on_turn_on:
    - logger.log: "Switch (GPIO18) Turned On!"
    on_turn_off:
    - logger.log: "Switch (GPIO18) Turned Off!"
  
  - platform: gpio
    name: "(GPIO08) LED"
    id: pin_GPIO08
    pin:
      number: GPIO08
      allow_other_uses: true
      inverted: yes
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - logger.log: "LED (GPIO08) Turned On!"
    on_turn_off:
    - logger.log: "LED (GPIO08) Turned Off!"

binary_sensor:
  - platform: gpio
    name: "(GPIO08) LED"
    pin:
      number: GPIO08
      allow_other_uses: true
    web_server:
      sorting_group_id: sorting_group_monitor

  - platform: gpio
    name: "(GPIO09)"
    pin:
      number: GPIO09
      allow_other_uses: true
    web_server:
      sorting_group_id: sorting_group_monitor

  - platform: gpio
    name: "(GPIO18)"
    pin:
      number: GPIO18
      allow_other_uses: true
    web_server:
      sorting_group_id: sorting_group_monitor
      
# END