substitutions:
  name: "esp32-c6-2-mic"
  friendly_name: "ESP32_C6_2-mic"

esphome:
  name: "esp32-c6-2-mic"
  friendly_name: "ESP32_C6_2-mic"
  platformio_options:
    build_flags: "-I2S_NUM_MAX=I2S_NUM_0 -I2S_MCLK_MULTIPLE_DEFAULT=I2S_MCLK_MULTIPLE_768"

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 8MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
    
external_components:
  - source: github://esphome/esphome@jesserockz-2023-409
    components: i2s_audio
    refresh: 0s
  - source: github://mafrosis/esphome-sound-level-meter@tmp
    components: [i2s, sound_level_meter]

logger:
  level: INFO
  baud_rate: 115200
  hardware_uart: USB_SERIAL_JTAG
  logs:
    sensor: INFO
    component: INFO
    esp-idf: ERROR
    template.sensor: INFO
    text_sensor: INFO

api:
  encryption:
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_portable
      password: !secret wifi_password_portable
  # Board will host Wifi by itself
  ap:
    ssid: "${friendly_name}"
    password: !secret fall_back_wifi_password
    manual_ip:
        static_ip: !secret ap_static_ip_portable
        gateway: !secret ap_static_gateway
        subnet: 255.255.255.0
        dns1: !secret ap_static_dns
        dns2: 8.8.8.8
  # When no WifI
  reboot_timeout: 900s
  # Do not fast connect when portable
  # fast_connect: true

# Do not use when portable
# captive_portal:

web_server:
  port: 80
  version: 3
  sorting_groups:
  - id: sorting_group_general
    name: "General"
    sorting_weight: -1
  - id: sorting_group_statistics
    name: "Statistics"
    sorting_weight: 10
  - id: sorting_group_calibration
    name: "Calibration Values"
    sorting_weight: 40
  - id: sorting_group_diagnostic
    name: "Diagnostic info"
    sorting_weight: 60
  - id: sorting_group_service
    name: "Service"
    sorting_weight: 90

#   Unsupported variant ESP32C6. !!!
i2s_audio:
  i2s_lrclk_pin: GPIO19
  i2s_bclk_pin: GPIO18

microphone:
  - platform: i2s_audio
    id: external_mic
    adc_type: external
    i2s_din_pin: GPIO20
    pdm: false

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 10s
    web_server:
      sorting_group_id: sorting_group_diagnostic

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "${friendly_name} WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 10s
    web_server:
      sorting_group_id: sorting_group_diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "${friendly_name}  WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    device_class: ""
    web_server:
      sorting_group_id: sorting_group_diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    bssid:
      name: "${friendly_name} Connected BSSID"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    mac_address:
      name: "${friendly_name} Mac Wifi Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic
    dns_address:
      name: "${friendly_name} DNS Address"
      web_server:
          sorting_group_id: sorting_group_diagnostic

button:
  - platform: restart
    name: "Restart"
    web_server:
      sorting_group_id: sorting_group_service

# https://gist.github.com/baldowl/a413c2a08c10bc62c1a72328caac98c1?permalink_comment_id=5496287#gistcomment-5496287
light:
  - platform: esp32_rmt_led_strip
    name: Status LED
    id: co2light
    pin: GPIO8
    rgb_order: GRB
    num_leds: 1
    chipset: ws2812
    effects:
      - random:
      - strobe:
      - flicker:
    web_server: 
      sorting_group_id: sorting_group_service

# END